# Numpy review homework

1. Make a numpy matrix from a Python list of lists...

In [3]:
import numpy as np
ls = [[9,8,7],[6,5,4],[3,2,1]]
mat = np.array(ls)
mat

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

2. Make a 3D numpy matrix from a Python list of lists of lists!

In [4]:
ls = [[[0,1],[2,3]],[[4,5],[6,7]],[[8,9],[10,11]]]
mat = np.array(ls)
mat

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

3. Create a 5x3 array of Gaussian random numbers. 

In [18]:
noise = np.random.randn(5,3)
noise

array([[ 0.68579759, -1.76454622, -0.50734714],
       [ 0.59531057, -0.06770099, -0.93428723],
       [-1.12051024, -0.84492869,  1.96069926],
       [-1.7270785 , -0.12950564, -0.8497218 ],
       [ 0.42520114,  0.8606911 ,  1.41532401]])

4. Write a script to go through the array created in 3. and announce (print) the value and its row and column indexes.

Hint: Use nested `for` loops - one to loop through the rows and one to loop through the columns.

In [19]:
for i in range(len(noise)):
    #print(noise[i])
    for j in range(len(noise[i])):
        print(noise[i,j])
        print(f'Location: {i,j}')

0.6857975878765163
Location: (0, 0)
-1.764546220539607
Location: (0, 1)
-0.5073471369503045
Location: (0, 2)
0.5953105658077735
Location: (1, 0)
-0.06770098538006855
Location: (1, 1)
-0.9342872332126789
Location: (1, 2)
-1.1205102427655835
Location: (2, 0)
-0.8449286917095321
Location: (2, 1)
1.9606992556902965
Location: (2, 2)
-1.7270784984083467
Location: (3, 0)
-0.1295056399206804
Location: (3, 1)
-0.8497217976282831
Location: (3, 2)
0.4252011377495098
Location: (4, 0)
0.8606910986528811
Location: (4, 1)
1.4153240090348145
Location: (4, 2)


5. Make an new array out of your random numbers such that the mean is 10 and the standard deviation is 3.

In [34]:
nums = noise *3
nums = nums + 10
print(nums.std())
print(nums.mean())

3.218630251201019
9.599479441659343


6. Count the number of values in your new array that are below 7.

In [25]:
count = 0
for i in range(len(nums)):
    for j in range(len(nums[i])):
        if nums[i,j] < 7:
            count += 1
count

3

7. Make a numpy sequence that has the even numbers from 2 up to (and including) 20.

In [28]:
ls = []

for i in range(21):
    if i%2 == 0:
        ls.append(i)

ar = np.array(ls)
ar

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

8. Get the second and third rows of your array.

In [32]:
nums[1:3]
#nums

array([[11.7859317 ,  9.79689704,  7.1971383 ],
       [ 6.63846927,  7.46521392, 15.88209777]])

9. Compute the mean of the columns of your array.

In [33]:
np.mean(nums[1:3])

9.794291334215105